[project]
name = "manga-image-translator"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
requires-python = ">=3.11"
license = { file="./LICENSE"}
dependencies = [
    "accelerate==1.2.0",
    "aiofiles==24.1.0",
    "aiohappyeyeballs==2.4.4",
    "aiohttp==3.11.10",
    "aioshutil==1.5",
    "aiosignal==1.3.1",
    "annotated-types==0.7.0",
    "antlr4-python3-runtime==4.9.3",
    "anyio==4.7.0",
    "appdirs==1.4.4",
    "arabic-reshaper==3.0.0",
    "attrs==24.2.0",
    "backports-cached-property==1.0.2",
    "bitsandbytes==0.45.0",
    "certifi==2024.8.30",
    "cffi==1.17.1",
    "charset-normalizer==3.4.0",
    "click==8.1.7",
    "colorama==0.4.6",
    "coloredlogs==15.0.1",
    "cryptography==44.0.0",
    "ctranslate2==4.5.0",
    "cython==3.0.11",
    "deepl==1.20.0",
    "distro==1.9.0",
    "editdistance==0.8.1",
    "einops==0.8.0",
    "fastapi==0.115.6",
    "filelock==3.16.1",
    "fire==0.7.0",
    "flatbuffers==24.3.25",
    "freetype-py==2.5.1",
    "frozenlist==1.5.0",
    "fsspec==2024.10.0",
    "ftfy==6.3.1",
    "fugashi==1.4.0",
    "groq==0.13.0",
    "h11==0.14.0",
    "httpcore==1.0.7",
    "httpx==0.27.2",
    "huggingface-hub==0.26.5",
    "humanfriendly==10.0",
    "idna==3.10",
    "imagehash==4.3.1",
    "imageio==2.36.1",
    "jaconv==0.4.0",
    "jinja2==3.1.4",
    "kornia-rs==0.1.7",
    "kornia==0.7.4",
    "langcodes==3.5.0",
    "langdetect==1.0.9",
    "language-data==1.3.0",
    "lazy-loader==0.4",
    "loguru==0.7.3",
    "manga-ocr==0.1.13",
    "marisa-trie==1.2.1",
    "markupsafe==3.0.2",
    "marshmallow==3.23.1",
    "mpmath==1.3.0",
    "multidict==6.1.0",
    "nest-asyncio==1.6.0",
    "networkx==3.4.2",
    "numpy==1.26.4",
    "omegaconf==2.3.0",
    "onnxruntime==1.20.1",
    "open-clip-torch==2.29.0",
    "openai==1.35.9",
    "opencv-python==4.10.0.84",
    "packaging==24.2",
    "pandas==2.2.3",
    "pillow==11.0.0",
    "propcache==0.2.1",
    "protobuf==5.29.1",
    "psutil==6.1.0",
    "py3langid==0.2.2",
    "pyclipper==1.3.0.post6",
    "pycparser==2.22",
    "pydantic-core==2.27.1",
    "pydantic==2.10.3",
    "pydensecrf@https://github.com/lucasb-eyer/pydensecrf/archive/refs/heads/master.zip",
    "pyhyphen==4.0.4",
    "pyperclip==1.9.0",
    "pyreadline3==3.5.4",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.0.1",
    "python-multipart==0.0.19",
    "pytz==2024.2",
    "pywavelets==1.8.0",
    "pyyaml==6.0.2",
    "regex==2024.11.6",
    "requests==2.32.3",
    "safetensors==0.4.5",
    "scikit-image==0.24.0",
    "scipy==1.14.1",
    "sentencepiece==0.2.0",
    "setuptools==75.6.0",
    "shapely==2.0.6",
    "six==1.17.0",
    "sniffio==1.3.1",
    "starlette==0.41.3",
    "sympy==1.13.1",
    "tensorboardx==2.6.2.2",
    "termcolor==2.5.0",
    "tifffile==2024.9.20",
    "timm==1.0.12",
    "tokenizers==0.21.0",
    "torch-summary==1.4.5",
    "torch@https://download.pytorch.org/whl/cu124/torch-2.5.1%2Bcu124-cp311-cp311-win_amd64.whl",
    "torchaudio@https://download.pytorch.org/whl/cu124/torchaudio-2.5.1%2Bcu124-cp311-cp311-win_amd64.whl",
    "torchvision@https://download.pytorch.org/whl/cu124/torchvision-0.20.1%2Bcu124-cp311-cp311-win_amd64.whl",
    "tqdm==4.67.1",
    "transformers==4.47.0",
    "typing-extensions==4.12.2",
    "tzdata==2024.2",
    "unidic-lite==1.0.8",
    "urllib3==2.2.3",
    "uvicorn==0.32.1",
    "wcwidth==0.2.13",
    "websockets==14.1",
    "wheel==0.45.1",
    "win32-setctime==1.2.0",
    "yarl==1.18.3",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = 'black'
multi_line_output = 3
line_length = 100
py_version = 310

[tool.setuptools]

packages = [
 "manga_translator",
]

package-dir = {"manga_translator"="manga_translator", ""="manga_translator"}
package-data = {"manga_translator"=["fonts/*.ttf", "fonts/*.ttc"]}

[find]
where = ["manga_translator"]
include = ["manga_translator*"]
namespaces = false

[project.scripts]
manga_translator = "manga_translator.__main__:main"

[tool.pylint]
disable = """
C,R,W,
c-extension-no-member
"""
additional-builtins = "display"
output-format = "colorized"
generated-members = ["torch.*", "cv2.*"]

[tool.pytest.ini_options]
addopts = "-ra -v -p no:faulthandler"
minversion = "6.0"
testpaths = ["test"]
